const express = require("express")
const server = express.Router()

const { a, search, genre_filter, home, genre, post, tweet, login, form, login_post, signin, uploading_meme, uploading_tweet, post_reaction, tweet_reaction } = require('../controller/controller')
server.get('/', home)
server.get('/genre', genre)
server.get('/post', post)
server.get('/tweet', tweet)
server.get('/login', login)
server.post('/login', login_post)
server.post('/signup', signin)
server.post('/search', search)
server.get('/form', form)
server.post('/uploading_meme', uploading_meme)
server.post('/uploading_tweet', uploading_tweet)
server.get('/meme_reaction/:id/:type', post_reaction)
server.get('/tweet_reaction/:id/:type', tweet_reaction)
server.get('/a', a)
server.get('/tweets/:tag', genre_filter)
module.exports = server